version: "3.5"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    networks:
      - money-net
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  scraper:
    container_name: scraper
    build:
      context: ./scraper
    networks:
      - money-net
    depends_on:
      - elasticsearch

  website:
    container_name: website
    build:
      context: ./website
    ports:
      - 80:80
    networks:
      - money-net

networks:
  money-net:
    driver: bridge
